sudo: true
language: python
python:
    - "2.7"

env:
    - BRANCH=develop 
    - DOCKER_BACKEND_FS=host 
    - DOCKER_STORAGE_DRIVER=aufs

# command to install dependencies
install: 
    - "pip install -r requirements.txt"
# This uses the travis-docker repository at
# https://github.com/moul/travis-docker
#    - curl -sLo - http://github.com/charlesvardeman/smartcontainers/raw/$TRAVIS_BRANCH/resources/install-docker.sh | sh -xe
    - curl -sLo - http://j.mp/install-travis-docker | sh -xe
#run tests
script:
    - py.test
    - ./run docker info
