# Docker setup is based on
# https://github.com/rocker-org/rocker/blob/56cb59cc262e9d2c02f9e11cfacab65f0b659c5f/.travis.yml#L17
sudo: required
dist: trusty
language: python
python:
    - "2.7"
services:
    - docker
env:
  global:
    - "HOST_IP=$(/sbin/ifconfig venet0:0 | grep 'inet addr' | awk -F: '{print $2}' | awk '{print $1}')"
    - DOCKER_HOST=tcp://$HOST_IP:2375
    - DOCKER_PORT_RANGE=2400:2500
    - SLIRP_PORTS=$(seq 2375 2500)

before_install:
    - docker pull phusion/baseimage

# command to install dependencies
install:
    - "pip install -r requirements.txt"

#run tests
script:
    - docker version
    - docker info
    - py.test -v
