# Docker setup is based on
# https://github.com/rocker-org/rocker/blob/56cb59cc262e9d2c02f9e11cfacab65f0b659c5f/.travis.yml#L17
sudo: required
dist: trusty
language: python
python:
    - "2.7"
services:
    - docker

before_install:
    - docker pull phusion/baseimage

# command to install dependencies
install:
    - "pip install tox-travis"

#run tests
script:
    - docker version
    - docker info
    - tox
