sudo: true
language: python
python:
    - "2.7"


# command to install dependencies
install: 
    - "pip install -r requirements.txt"
# This uses the travis-docker repository at
# https://github.com/moul/travis-docker
    - curl -sLo - http://github.com/charlesvardeman/smartcontainers/raw/dev_0.02/resources/install-docker.sh | sh -xe
# run tests
script: 
    - py.test
